### ISSUE TITLE
undefined local variable or method `reset_mailer' 

### ISSUE THREAD

**Issue by alec-c4** [email-spec/email-spec#221]
Hey!
After upgrade email_spec from 2.2.0 to 2.2.1 i've got following issue https://github.com/Shopify/better-html/issues/96 How to fix it?

**Comment by ckhall** [comment]
experiencing the same problem after upgrading from 2.2.0 to 2.2.1

test_helper.rb

```
require "minitest-matchers"
require "email_spec"

class ActiveSupport::TestCase
  # other includes
  include EmailSpec::Helpers
  include EmailSpec::Matchers
  # other includes
end
```

tests using `reset_mailer` fail with the error:

```
NameError: undefined local variable or method `reset_mailer' for #<#<Class:0x00007f7aa5aeee90>:0x00007f7aa2d4eb20>
```

attempted to move includes to top/bottom of include list in `class ActiveSupport::TestCase` as well as adding includes within the tests themselves but error still raised.  reverting to 2.2.0 fixes the issue.

**Comment by ckhall** [comment]
also fails when pointing gemfile to github directly:

`gem "email_spec", git: "https://github.com/email-spec/email-spec"`

**Comment by ut** [comment]
I can confirm this issue (Rails 5)

**Comment by gravitystorm** [comment]
Other than pinning to 2.2.0, does anyone have any workarounds, or any insight as to what has caused this and what might be the solution?

**Comment by alec-c4** [comment]
@etagwerker may i ask you to check this issue?

**Comment by alec-c4** [comment]
it looks like this commit https://github.com/email-spec/email-spec/commit/58f94e2659a71607a710bad6a1faf8a39b7230a2 is the source of the problem

**Comment by cgunther** [comment]
What `config.action_mailer.delivery_method` is set in your test environments? Mine is `:test` and I've had no issues running with that across multiple projects.

There's a separate codepath for `:activerecord`, so maybe the issue is there if you all coincidentally are using that delivery method? The test suite doesn't seem to cover that path, which could hide an issue. I'm not even seeing that Rails/ActionMailer supports `:activerecord` out of the box, so is that coming from an external gem?

**Comment by gravitystorm** [comment]
> What `config.action_mailer.delivery_method` is set in your test environments? Mine is `:test` and I've had no issues running with that across multiple projects.

I have the `delivery_method` as `:test` on both my affected apps. 

If there's anything I can do to help debug this, please let me know. One of my apps is an open-source prototype, and it's possible to use that to recreate the error - https://gitlab.com/gravitystorm/coppermill/ - if you release the pin in the Gemfile, run bundle update, then `bundle exec rspec` will fail.

**Comment by cgunther** [comment]
Thanks, I can reproduce it. Looks like my projects have some other gems that also eager load actionmailer (what #219 corrected in this gem), hiding this problem for me.

I understand why it's happening, though I'm not sure what the fix is at the moment. Here's a summary incase anyone else has any ideas in the meantime.

At the point you [`require "email_spec/rspec"`](https://gitlab.com/gravitystorm/coppermill/-/blob/28fe22b31f34ed786c40004c75e60511a3629275/spec/rails_helper.rb#L14), actionmailer is not yet loaded, so when the [helpers are included into RSpec](https://github.com/email-spec/email-spec/blob/f9496fc3022a8545fe95f3cf869380a899a56729/lib/email_spec/rspec.rb#L2), this gem hasn't yet included the [`MailerDeliveries`](https://github.com/email-spec/email-spec/blob/f9496fc3022a8545fe95f3cf869380a899a56729/lib/email_spec/deliveries.rb#L11-L17) module that defines `reset_mailer` into the `EmailSpec::Helpers` module.

Later, actionmailer is loaded, which now [includes the `EmailSpec::MailerDeliveries` module into the `EmailSpec::Helpers` module](https://github.com/email-spec/email-spec/blob/f9496fc3022a8545fe95f3cf869380a899a56729/lib/email_spec/deliveries.rb#L86).

However, Ruby doesn't seem to apply future includes into classes/modules the parent was previously included. Therefore, it's as if RSpec is frozen with the `EmailSpec::Helpers` module WITHOUT `EmailSpec::MailerDeliveries`, since that was the state of the module at the time it was included into RSpec.

This seems to be a quirk of Ruby, nothing specific to RSpec, as demonstrated by this [script](https://gist.github.com/cgunther/b49a590c3fab2746ad8b4721d07e7ad9). Even though we've included `B` into `A`, which itself is included in `Foo`, since `B` was included in `A` AFTER `A` was included in `Foo`, `Foo` doesn't seem to treat `B` as being an ancestor, hence the error when we call a method defined in `B`. If you move the `A.include(B)` line above the `Foo` class definition, then it works.

I'll give some thought to what a fix could be. #219 corrected a real issue, so I don't think simply reverting it is the right fix. If actionmailer is loaded too early, then when you try to enable actionmailer configs in a `new_framework_defaults` file of Rails, they don't actually take effect, as actionmailer was loaded before your initializer, and therefore it already copied all the configuration internally, and any other changes to configuration in an initializer via `Rails.application.config` have no effect.

**Comment by RobertGauld** [comment]
> However, Ruby doesn't seem to apply future includes into classes/modules the parent was previously included. Therefore, it's as if RSpec is frozen with the `EmailSpec::Helpers` module WITHOUT `EmailSpec::MailerDeliveries`, since that was the state of the module at the time it was included into RSpec.
> 
> This seems to be a quirk of Ruby, nothing specific to RSpec, as demonstrated by this [script](https://gist.github.com/cgunther/b49a590c3fab2746ad8b4721d07e7ad9). Even though we've included `B` into `A`, which itself is included in `Foo`, since `B` was included in `A` AFTER `A` was included in `Foo`, `Foo` doesn't seem to treat `B` as being an ancestor, hence the error when we call a method defined in `B`. If you move the `A.include(B)` line above the `Foo` class definition, then it works.

This works so it's not completely stupid, but it does feel a bit yucky and I'm not sure why.

```ruby
module A
end

module B
  def bar
    'bar'
  end
end

class Foo
  include A

  def method_missing(method_name, *args, **kwargs, &block)
    puts "method_missing(#{method_name.inspect}, #{args.inspect}, #{kwargs.inspect}"
    if method_name == :bar
      Foo.include A
      send method_name, *args
    else
      super
    end
  end
end

A.include(B)

puts Foo.new.bar
puts Foo.new.bar
# undefined method `bar' for #<Foo:0x00007fc43e0d4940> (NoMethodError)
```

```diff
11a12,21
> 
>   def method_missing(method_name, *args, **kwargs, &block)
>     puts "method_missing(#{method_name.inspect}, #{args.inspect}, #{kwargs.inspect}"
>     if method_name == :bar
>       Foo.include A
>       send method_name, *args
>     else
>       super
>     end
>   end
15a26
> puts Foo.new.bar
```

**Comment by cgunther** [comment]
Unfortunately I don't think that would work, that was an oversimplified example, but thanks for the idea, seemed like it had some promise as I went down that path.

In our case, when `method_missing` gets called, we'd have to include the appropriate deliveries module (and re-call the method), but wrapped in the `ActiveSupport.on_load(:action_mailer)` block to avoid prematurely loading ActionMailer, which means `method_missing` could return before that block gets called to re-call the method (ie. `reset_mailer`).

Spending some more time on this, I'm still stumped. ActionMailer is lazily loaded in tests, so at the point `reset_mailer` is called in the `before` hook (using @gravitystorm's app) ActionMailer may not even be loaded yet (it could load later in the process of running the test). I'm starting to wonder if calling methods like `reset_mailer` need to trigger loading ActionMailer itself, rather than waiting on Rails to load it, but still not simply upon requiring this library (as was the case prior to #219).

**Comment by axlekb** [comment]
I just started encountering this issue but I have `2.2.1` installed since September working.
I found that it started happening when I upgraded `premailer-rails` from `1.11.1` to `1.12.0`.  Hopefully that's a useful data point to someone.

**Comment by cgunther** [comment]
premailer-rails v1.12.0 fixed eagerloading ActionMailer (https://github.com/fphilipe/premailer-rails/pull/260). Very similar in concept to what my PR introducing this issue here intended to do. Eager loading ActionMailer can cause headaches in the future, namely around trying to configure it via initializers.

In premailer-rails v1.11.1, ActionMailer was eagerly loaded, so email-spec could hook in properly, even with email-spec v2.2.1. With premailer-rails v1.12.0, ActionMailer is no longer eager loaded, and now email-spec seems to try hooking in too late.

I'm still rather stumped on the proper fix here. Before my PR, email-spec caused ActionMailer to be loaded too early, causing problems, and now ActionMailer is loaded too late, causing different problems.

**Comment by theycallmeswift** [comment]
Did this ever get resolved? We are seeing the same intermittent error where a test gets run before ActionMailer is loaded, resulting in the error below:

```
NameError: undefined local variable or method `reset_mailer' 
```

Would be great to have a recommended official fix.

**Comment by alec-c4** [comment]
Hey! Any news with this issue? @etagwerker @bmabey @cgunther

**Comment by thoughtbot-boost-support** [comment]
I'm having this issue as well

**Comment by cgunther** [comment]
Could you all test with #224 (`gem "email_spec", git: "https://github.com/cgunther/email-spec", branch: "fix-undefined-reset-mailer-2"`)?

I think that might resolve the issue. Using @gravitystorm's example application, the tests now pass, no longer erroring about `reset_mailer`.

**Comment by alec-c4** [comment]
@cgunther works fine, thanks! May I ask you to release it a soon as possible? :)

**Comment by gravitystorm** [comment]
@cgunther I can confirm that the proposed fix also works for another (internal) app that I have over here :+1:

**Comment by RobertGauld** [comment]
@cgunther works for me too.

**Comment by thoughtbot-boost-support** [comment]
@cgunther that works for me as well
