### PR TITLE
Defer accommodating different delivery methods to runtime

### LINKED ISSUE #221: undefined local variable or method `reset_mailer'
Hey!
After upgrade email_spec from 2.2.0 to 2.2.1 i've got following issue https://github.com/Shopify/better-html/issues/96 How to fix it?

### PR DESCRIPTION
**Pull request by cgunther**
After #219, ActionMailer became lazily loaded, leading to this library hooking into RSpec potentially before including the module specific to the delivery method in use, so RSpec never saw the delivery method-specific module, leading to errors as documented in #221.

Now, the individual methods (ie. `reset_mailer`, `deliveries`) are responsible for branching based on the correct delivery method, defining their corresponding implementation.

Thinking longer term, there's no guarantee a single delivery method is used across the board (though that's likely the most common scenario), so rather than branching, we should probably iterate through all supported delivery methods. #216 touches on this, where instead of assuming Pony OR ActionMailer, both should likely be supported simultaneously, searching each for a given email, and resetting all.

Fixes #221

### CODE REVIEW

**Review by etagwerker — APPROVED** [review]
@cgunther Looks good, thank you!
